2019-09-13 14:15:30.317379: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2019-09-13 14:15:30.352221: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
2019-09-13 14:15:30.359482: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x56321825eb00 executing computations on platform Host. Devices:
2019-09-13 14:15:30.359527: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-09-13 14:15:30.488233: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x563214c42a60 executing computations on platform CUDA. Devices:
2019-09-13 14:15:30.488296: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Quadro GV100, Compute Capability 7.0
2019-09-13 14:15:30.490724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: Quadro GV100 major: 7 minor: 0 memoryClockRate(GHz): 1.627
pciBusID: 0000:2d:00.0
totalMemory: 31.72GiB freeMemory: 30.81GiB
2019-09-13 14:15:30.490759: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-09-13 14:15:30.495429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-13 14:15:30.495455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-09-13 14:15:30.495467: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-09-13 14:15:30.497750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 29970 MB memory) -> physical GPU (device: 0, name: Quadro GV100, pci bus id: 0000:2d:00.0, compute capability: 7.0)
2019-09-13 14:15:34.716822: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
1287964
[      0       1       2 ... 1287961 1287962 1287963]
[[1.42010002e+01 1.36470003e+01 1.35600004e+01 ... 1.34940000e+01
  1.35240000e+01 2.31071287e-01]
 [1.52720003e+01 1.46890001e+01 1.46199999e+01 ... 1.45640000e+01
  1.45340000e+01 2.50156382e-02]
 [1.45600004e+01 1.39490004e+01 1.38900003e+01 ... 1.38140000e+01
  1.39120000e+01 1.21588542e-02]
 ...
 [1.17799997e+01 1.12049999e+01 1.10889997e+01 ... 1.10090000e+01
  1.11170000e+01 3.90151217e-01]
 [1.02880001e+01 9.57100010e+00 9.40699959e+00 ... 9.34100000e+00
  9.46400000e+00 1.54063787e-01]
 [9.54800034e+00 9.02200031e+00 8.90299988e+00 ... 8.82500000e+00
  8.94300000e+00 7.28459370e-01]]
17.824765284426462
-1.0782020547003095
here
[[0.7478831 ]
 [0.58119725]
 [0.70910222]
 ...
 [0.57057133]
 [0.68445895]
 [0.59867118]]
[157157, 64152, 87579, 128674, 139935, 59038, 96282, 55318, 141478, 85047]
Traceback (most recent call last):
  File "T_PDM_p.py", line 513, in <module>
    plot_pdfs(pred_means,pred_weights,pred_std)
  File "T_PDM_p.py", line 269, in plot_pdfs
    fs = plot_normal_mix(pred_weights[obj][i], pred_means[obj][i],
IndexError: index 157157 is out of bounds for axis 0 with size 37884
